;;; Automatically generated by ‘recentf’ on Tue May  9 12:58:04 2023.

(setq recentf-list
      '(
        "/home/tedflint/Dropbox/emacs/config/literate-emacs-config.org"
        "/home/tedflint/Dropbox/emacs/config/bookmarks"
        "/home/tedflint/Dropbox/universe/zettelkasten/20230430135243-canonical_task_list.org"
        "/home/tedflint/.emacs.d/var/diary"
        "/home/tedflint/Dropbox/emacs/org/agenda.org"
        "/home/tedflint/.emacs.d/var/elfeed/db/index"
        "/home/tedflint/Dropbox/emacs/config/recent-files.txt"
        "/home/tedflint/Dropbox/universe/room-office-dropbox/desk-village-hall/agendas/agendas-2023/vh-agenda-05-2023.tex"
        "/home/tedflint/Dropbox/universe/room-office-dropbox/desk-village-hall/agendas/agendas-2023/vh-agenda-05-2023.txt"
        "/home/tedflint/Dropbox/universe/room-office-dropbox/desk-village-hall/agendas/agendas-2023/vh-agenda-05-2023.pdf"
        "/home/tedflint/Dropbox/universe/zettelkasten/20210801190646-ideas.org"
        "/home/tedflint/Desktop/todo-2-may-2023.html"
        "/home/tedflint/.emacs.d/var/auto-save/sessions/3476-T440p~"
        "/home/tedflint/.arbtt/categorize.cfg"
        "/home/tedflint/Dropbox/emacs/config/.bashrc"
        "/home/tedflint/.emacs.d/var/elgrep-data.el"
        "/home/tedflint/Dropbox/universe/zettelkasten/20230406131256-home.org"
        "/home/tedflint/Dropbox/universe/zettelkasten/20230417142038-theatre.org"
        "/home/tedflint/Dropbox/universe/zettelkasten/20230430221440-concerts.org"
        "/home/tedflint/Dropbox/universe/zettelkasten/20230430220914-cars.org"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
